### ISSUE TITLE
Setup command typo

### ISSUE THREAD

**Issue by loiclaudet** [clintonwoo/hackernews-remix-react#2]
Hi,
Wanted to point out that the folder and project name both have a typo in the setup command.
`react` and `remix` should be reversed.

Here is the diff (don't get access right to make a PR) :
-`git clone https://github.com/clintonwoo/hackernews-react-remix.git && cd hackernews-react-remix && npm install && npm run dev`

+`git clone https://github.com/clintonwoo/hackernews-remix-react.git && cd hackernews-remix-react && npm install && npm run dev`

Cheers.

**Comment by clintonwoo** [comment]
Thanks for that, I've fixed it!
